version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/auth
    ports:
      - 3000:3000
  plantuml-server:
    image: plantuml/plantuml-server
    ports:
      - '9999:8080'
