version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/auth
    command: sh -c "cd auth-api-fr && yarn install && yarn dev"
    ports:
      - 3000:3000
