@startuml auth
title 認証処理
"他システム" -> "画面" : 認証要求\n/auth?systemCd=システムコード
"画面" -> "API" : システムコード判定API呼出
"DB" -> "API" : **他シスURL**取得 (key:システムコード)
"API" -> "画面" : **他シスURL**、判定結果返却
alt システムコード有
"画面" -> "画面" : 認可コード有無判定 (Local Storage)
alt 認可コード有
"画面" -> "API" : ユーザ情報取得API呼出
"KVS" -> "API" : **認証情報**取得 (key:**認可コード**)
"API" -> "KVS" : **認証情報**削除 (key:**認可コード**)
"DB" -> "API" : **ユーザ情報**取得 (key:**認証情報**)
alt ユーザ情報有
"API" -> "API" : **認可コード**発行
"API" -> "KVS" : **認証情報**登録 (key:**認可コード**)
"API" -> "画面" : **認可コード**、**ユーザ情報**返却
"画面" -> "画面" : **認可コード**保管 (Local Storage)
"画面" -> "他システム" : **ユーザ情報**返却
else ユーザ情報無
note over 他システム, KVS
**認可コード無**フローと同様
end note
end
else 認可コード無
"画面" -> "画面" : 初期表示
"画面" -> "画面" : 認証情報入力
"画面" -> "API" : 認証API呼出
"DB" -> "API" : **ユーザ情報**取得
alt ユーザ情報有
"API" -> "API" : **認可コード**発行
"API" -> "KVS" : 認証情報登録 (key:**認可コード**)
"API" -> "画面" : **認可コード**、**ユーザ情報**返却
"画面" -> "画面" : **認可コード**保管 (Local Storage)
"画面" -> "他システム" : **ユーザ情報**返却
else ユーザ情報無
"API" -> "画面" : エラーメッセージ返却
"画面" -> "画面" : エラーメッセージ表示
end
end
else システムコード無
"画面" -> "画面" : エラーメッセージ表示
end
@enduml